users:
  build: .
  command: supervisor ./services/users/index.js
  environment:
    - OFFLINE_MODE=true
    - USER_DATA_PATH=/var/userservice/userdata/
    - SERVICE_NAME=users
    - RABBITMQ_HOST=rabbitmq
  ports:
    - "9120:9120"
  volumes:
    - /Users/jhaeger/code/personal/ContextEngine/data/userSpecific:/var/userservice/userdata/
  links:
    - rabbitmq

eventstamper:
  build: .
  command: supervisor ./services/eventStamper/index.js
  environment:
    - OFFLINE_MODE=true
    - SERVICE_NAME=eventStamper
    - RABBITMQ_HOST=rabbitmq
  links:
    - rabbitmq

historicalevents:
  build: .
  command: supervisor ./services/historicalEventService/index.js
  links:
    - rabbitmq
    - users
  ports:
    - "9110:9110"
  volumes:
    - /Users/jhaeger/code/personal/ContextEngine/data/userSpecific:/var/userservice/userdata/
  environment:
    - SERVICE_NAME=historicalEventService
    - USER_DATA_PATH=/var/userservice/userdata/
    - OFFLINE_MODE=true
    - RABBITMQ_HOST=rabbitmq

fsm:
  build: .
  command: supervisor ./services/finiteStateMachines/index.js
  links:
    - rabbitmq
    - users
    - historicalevents
  ports:
    - "9111:9111"
  environment:
    - OFFLINE_MODE=true
    - RABBITMQ_HOST=rabbitmq
    - SERVICE_NAME=finiteStateMachines

cron:
  build: .
  command: supervisor ./services/cron/index.js
  environment:
    - OFFLINE_MODE=true
    - SERVICE_NAME=cron
    - RABBITMQ_HOST=rabbitmq
  links:
    - rabbitmq

notifier:
  build: .
  command: supervisor ./services/notifier/index.js
  environment:
    - OFFLINE_MODE=true
    - SERVICE_NAME=notifier
    - RABBITMQ_HOST=rabbitmq
  links:
    - rabbitmq
    - users

webfrontend:
  build: .
  command: supervisor ./services/webFrontEnd/index.js
  links:
    - rabbitmq
    - users
    - historicalevents
    - fsm
  ports:
    - "9005:9005"
  environment:
    - SERVICE_NAME=webFrontEnd
    - OFFLINE_MODE=true
    - RABBITMQ_HOST=rabbitmq

contextengine:
  build: .
  links:
    - rabbitmq
    - users
    - historicalevents
    - fsm
  environment:
    - OFFLINE_MODE=true
    - RABBITMQ_HOST=rabbitmq

rabbitmq:
  image: tutum/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_PASS=admin
